sudo: required
services:
  - docker

before_install:
  - docker build -t rahul6004/react-project -f Dockerfile.dev .

script:
  - docker run -e CI=true rahul6004/react-project npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-south-1-637423408616"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

